development:
    adapter: postgresql
    database: semat_development
    username: rofy
    password:
    host: localhost
test:
    adapter: postgresql
    database: semat_test
    username: rofy
    password: 
    host: localhost

production:
    adapter: postgresql
    database: semat_production
    username: rofy
    password:
    host: localhost
